# Generated by Django 3.1.4 on 2021-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=16, null=True)),
                ('model', models.CharField(max_length=16, null=True)),
                ('nrRejestracyjny', models.CharField(default='', max_length=10, unique=True)),
                ('rokProdukcji', models.PositiveSmallIntegerField(default=1900)),
                ('opis', models.TextField(blank=True, default='', null=True)),
                ('obraz', models.ImageField(blank=True, null=True, upload_to='zjdecia')),
                ('przegladTechniczny', models.DateField()),
                ('obslugaOkresowaData', models.DateField()),
                ('obslugaOkresowaKM', models.PositiveSmallIntegerField(default=0)),
                ('rocznikOponZimowych', models.PositiveSmallIntegerField(default=2000)),
                ('rocznikOponLetnich', models.PositiveSmallIntegerField(default=2000)),
                ('rozmiarOpon', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
