# Generated by Django 3.1.4 on 2020-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mark',
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='nrRejestracyjny',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rokProdukcji',
            field=models.PositiveSmallIntegerField(default=1900),
        ),
    ]
