# Generated by Django 3.1.4 on 2021-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210119_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='obslugaOkresowaKM',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
