# Generated by Django 3.1.4 on 2020-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201207_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='opis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
