# Generated by Django 3.1.4 on 2021-01-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_przegladtechniczny'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='obslugaOkresowaData',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='car',
            name='rocznikOponLetnich',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='car',
            name='rocznikOponZimowych',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='car',
            name='rozmiarOpon',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
