# Generated by Django 3.1.4 on 2021-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210119_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nrWewnetrzny',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='przebiegPojazdu',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
